services:
  minecraft:
    container_name: minecraft
    image: opisek/mc-paper-docker-lite:latest
    volumes:
      - /srv/minecraft:/app/minecraft # change /srv/minecraft to the directory you want to store minecraft files in
    ports: 
      - 25565:25565
    environment:
      - EULA=false      # change this to true if you agree to minecraft eula https://www.minecraft.net/en-us/eula
      - VERSION=latest  # minecraft version or "latest"
      - CHANNEL=default # change this to experimental for experimental paper builds
      - GRACE=180       # amount of time in seconds of nobody being online before stopping the server
      - XMS=8G          # minimum amount of ram to allocate to the server
      - XMX=8G          # maximum amount of ram to allocate to the server
      - MC_UID=9999     # minecraft files user id
      - MC_GID=9999     # minecraft files group id
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
